name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    concurrency:
        group:${{github.workflow}}-${{github.ref}}
    steps:
      - name: ⬇️ Checkout repository code
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📥 Install dependencies
        run: npm install

      - name: ⚙️ Build project
        run: npm run build

      - name: 🚀 Deploy
        # Example using a common deploy action from the Marketplace
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          # Secrets are used to store sensitive information like API tokens
          api_token: ${{ secrets.DEPLOY_API_TOKEN }}
        
          environment_url: https://easydecohome.github.io/forged-by-fire-homes/
